export const adminRoutes = {
  login: "/admin/login",
  forgotPassword: "/admin/forgot-password",
  resetPassword: "/admin/reset-password",
  dashboard: "/admin/dashboard",
  events: "/admin/events",
  eventsPending: "/admin/events/pending",
  createEvent: "/admin/events/create",
  event: (id: string) => `/admin/events/${id}`,
  editEvent: (id: string) => `/admin/events/${id}/edit`,
  eventOverview: (id: string) => `/admin/events/${id}/overview`,
  eventBookings: (id: string, segmentId?: string) =>
    segmentId
      ? `/admin/events/${id}/bookings?segmentId=${segmentId}`
      : `/admin/events/${id}/bookings`,
  eventAttendees: (id: string) => `/admin/events/${id}/attendees`,
  eventSegments: (id: string) => `/admin/events/${id}/segments`,
  eventCheckin: (id: string) => `/admin/events/${id}/checkin`,
  eventPromoCodes: (id: string) => `/admin/events/${id}/promo-codes`,
  eventAnalytics: (id: string) => `/admin/events/${id}/analytics`,
  users: "/admin/users",
  user: (id: string) => `/admin/users/${id}`,
  organizers: "/admin/organizers",
  organizersPending: "/admin/organizers/pending",
  organizer: (id: string) => `/admin/organizers/${id}`,
  orders: "/admin/orders",
  ordersRefunds: "/admin/orders/refunds",
  finance: "/admin/finance",
  financePayouts: "/admin/finance/payouts",
  paymentGateways: "/admin/payment-gateways",
  payments: "/admin/payments",
  refunds: "/admin/refunds",
  analytics: "/admin/analytics",
  promoCodes: "/admin/promo-codes",
  categories: "/admin/categories",
  cities: "/admin/cities",
  venues: "/admin/venues",
  homepage: "/admin/homepage-control",
  heroBanners: "/admin/hero-banners",
  aboutTeam: "/admin/about-team",
  featuredEvents: "/admin/featured-events",
  trendingEvents: "/admin/trending-events",
  seo: "/admin/seo",
  notifications: "/admin/notifications",
  reports: "/admin/reports",
  auditLogs: "/admin/audit-logs",
  roles: "/admin/roles-permissions",
  settings: "/admin/settings",
  security: "/admin/security",
} as const;

export const ADMIN_PAGE_TITLES: Record<string, string> = {
  [adminRoutes.dashboard]: "Dashboard",
  [adminRoutes.events]: "All events",
  [adminRoutes.eventsPending]: "Pending approval",
  [adminRoutes.users]: "Users",
  [adminRoutes.organizers]: "Organizers",
  [adminRoutes.organizersPending]: "Pending organizers",
  [adminRoutes.orders]: "All orders",
  [adminRoutes.ordersRefunds]: "Refunds",
  [adminRoutes.finance]: "Revenue",
  [adminRoutes.financePayouts]: "Payouts",
  [adminRoutes.paymentGateways]: "Payment Gateways",
  [adminRoutes.analytics]: "Analytics",
  [adminRoutes.promoCodes]: "Promo codes",
  [adminRoutes.settings]: "Settings",
  [adminRoutes.featuredEvents]: "Featured events",
  [adminRoutes.trendingEvents]: "Trending events",
  [adminRoutes.heroBanners]: "Hero banners",
  [adminRoutes.aboutTeam]: "About page team",
  [adminRoutes.cities]: "Cities",
  [adminRoutes.venues]: "Venues",
  [adminRoutes.homepage]: "Homepage control",
};
