export const routes = {
  home: "/",
  events: "/events",
  event: (slug: string) => `/event/${slug}`,
  categories: "/categories",
  about: "/about",
  faq: "/faq",
  contact: "/contact",
  terms: "/terms",
  privacy: "/privacy",
  refundPolicy: "/refund-policy",
  search: "/search",
  cart: "/cart",
  checkout: "/checkout",
  checkoutSuccess: "/checkout/success",
  checkoutFailed: "/checkout/failed",
  checkoutPaymentMock: "/checkout/payment/mock",
  checkoutPaymentSuccess: "/checkout/payment/success",
  checkoutPaymentFailed: "/checkout/payment/failed",
  checkoutPaymentCancelled: "/checkout/payment/cancelled",
  ticket: (id: string) => `/tickets/${id}`,
  login: "/login",
  register: "/register",
  checkEmail: "/check-email",
  verifyEmail: "/verify-email",
  forgotPassword: "/forgot-password",
  dashboard: "/dashboard",
  dashboardTickets: "/dashboard/tickets",
  dashboardOrders: "/dashboard/orders",
  dashboardSettings: "/dashboard/settings",
  organizer: {
    login: "/organizer/login",
    register: "/organizer/register",
    pending: "/organizer/pending",
    rejected: "/organizer/rejected",
    dashboard: "/organizer/dashboard",
    events: "/organizer/events",
    createEvent: "/organizer/events/create",
    eventOverview: (id: string) => `/organizer/events/${id}/overview`,
    editEvent: (id: string) => `/organizer/events/${id}/edit`,
    eventAttendees: (id: string) => `/organizer/events/${id}/attendees`,
    eventCheckin: (id: string) => `/organizer/events/${id}/checkin`,
    eventPromoCodes: (id: string) => `/organizer/events/${id}/promo-codes`,
    eventAnalytics: (id: string) => `/organizer/events/${id}/analytics`,
    analytics: "/organizer/analytics",
    payouts: "/organizer/payouts",
    settings: "/organizer/settings",
    checkin: "/organizer/checkin",
  },
  organizerProfile: (slug: string) => `/organizers/${slug}`,
  admin: {
    events: "/admin/events",
    eventsPending: "/admin/events/pending",
    createEvent: "/admin/events/create",
    event: (id: string) => `/admin/events/${id}`,
    editEvent: (id: string) => `/admin/events/${id}/edit`,
  },
} as const;
