import {
  LayoutDashboard,
  Calendar,
  Users,
  Building2,
  ShoppingBag,
  CreditCard,
  BarChart3,
  Tags,
  MapPin,
  Landmark,
  Home,
  Star,
  Search,
  Bell,
  FileText,
  Shield,
  Settings,
  ScrollText,
  KeyRound,
} from "lucide-react";
import { adminRoutes } from "@/config/admin-routes";

export const ADMIN_NAV = [
  { href: adminRoutes.dashboard, label: "Dashboard", icon: LayoutDashboard },
  { href: adminRoutes.events, label: "Events", icon: Calendar },
  { href: adminRoutes.eventsPending, label: "Pending", icon: Calendar },
  { href: adminRoutes.users, label: "Users", icon: Users },
  { href: adminRoutes.organizers, label: "Organizers", icon: Building2 },
  { href: adminRoutes.orders, label: "Orders", icon: ShoppingBag },
  { href: adminRoutes.payments, label: "Payments", icon: CreditCard },
  { href: adminRoutes.analytics, label: "Analytics", icon: BarChart3 },
  { href: adminRoutes.categories, label: "Categories", icon: Tags },
  { href: adminRoutes.cities, label: "Cities", icon: MapPin },
  { href: adminRoutes.venues, label: "Venues", icon: Landmark },
  { href: adminRoutes.homepage, label: "Homepage", icon: Home },
  { href: adminRoutes.featuredEvents, label: "Featured events", icon: Star },
  { href: adminRoutes.seo, label: "SEO", icon: Search },
  { href: adminRoutes.notifications, label: "Notifications", icon: Bell },
  { href: adminRoutes.reports, label: "Reports", icon: FileText },
  { href: adminRoutes.auditLogs, label: "Audit logs", icon: ScrollText },
  { href: adminRoutes.roles, label: "Roles", icon: KeyRound },
  { href: adminRoutes.security, label: "Security", icon: Shield },
  { href: adminRoutes.settings, label: "Settings", icon: Settings },
] as const;
